import Dance from "./Dance";
import Ranking from "./Rank";

type SingleDanceResult = {
    event: string; // e.g. "Adult Open Standard"
    dance: Dance;
    rankings: Ranking[];
    rawScore: number[][]; // tables generated by; rules similar to o2cm results
    rankCount: number[][];
}

export default SingleDanceResult;